version: '2'

services:
  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    env_file: env.unifi
    environment:
      - MEM_LIMIT=1024M
    volumes:
      - ./data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 9876:6789
    restart: unless-stopped
